version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:

  PostgreSQL:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: donbenn/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media 
    depends_on:
      - PostgreSQL  
    
  frontend:
    env_file: .env
    image: donbenn/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static

  nginx:
    image: donbenn/foodgram_nginx
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - static_volume:/static
      - media_volume:/media
      - ../templates/:/usr/share/nginx/html/redoc/