# Generated by Django 3.2.16 on 2025-01-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_rename_favorites_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
    ]
