# Generated by Django 3.2.16 on 2025-01-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0006_auto_20250108_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
