# Generated by Django 3.2.16 on 2025-01-13 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0008_alter_ingredientrecipe_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_subscribed',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/users/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
