# Generated by Django 3.2.16 on 2025-01-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0010_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='usrname_email_constraint',
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='username_email_constraint'),
        ),
    ]
