# Generated by Django 3.2.16 on 2025-01-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0012_auto_20250118_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'ordering': ('recipe',), 'verbose_name': 'Ингредиент рецепта', 'verbose_name_plural': 'Ингредиенты рецепта'},
        ),
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'ordering': ('recipe',), 'verbose_name': 'Тег рецепта', 'verbose_name_plural': 'Тэги рецепта'},
        ),
    ]
